// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8onM9HEUZGf0o3WMIejBIQGgGa3qiEM4',
    appId: '1:876012556988:web:f7ba827d9ee90483f036b9',
    messagingSenderId: '876012556988',
    projectId: 'foodly-flutter-c1019',
    authDomain: 'foodly-flutter-c1019.firebaseapp.com',
    storageBucket: 'foodly-flutter-c1019.appspot.com',
    measurementId: 'G-0ZEZE3G054',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkhcfdzVrqaZBGd8wbTNCv2YRBdBvupcs',
    appId: '1:876012556988:android:7713139e84bf8386f036b9',
    messagingSenderId: '876012556988',
    projectId: 'foodly-flutter-c1019',
    storageBucket: 'foodly-flutter-c1019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0qO7nKMIFAWWwy4Av5jWlIGf2al6A8Q',
    appId: '1:876012556988:ios:d4f24c227162ed15f036b9',
    messagingSenderId: '876012556988',
    projectId: 'foodly-flutter-c1019',
    storageBucket: 'foodly-flutter-c1019.appspot.com',
    iosBundleId: 'com.example.foody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq0qO7nKMIFAWWwy4Av5jWlIGf2al6A8Q',
    appId: '1:876012556988:ios:5391ce80ce04f612f036b9',
    messagingSenderId: '876012556988',
    projectId: 'foodly-flutter-c1019',
    storageBucket: 'foodly-flutter-c1019.appspot.com',
    iosBundleId: 'com.example.foody.RunnerTests',
  );
}
